export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";

export const HOME_PLAYLISTS_SUCCESS = "HOME_PLAYLISTS_SUCCESS";
export const HOME_PLAYLISTS_FAIL = "HOME_PLAYLISTS_FAIL";
export const HOME_PLAYLISTS_REQUEST = "HOME_PLAYLISTS_REQUEST";

export const HOME_CATEGORIES_SUCCESS = "HOME_CATEGORIES_SUCCESS";
export const HOME_CATEGORIES_FAIL = "HOME_CATEGORIES_FAIL";
export const HOME_CATEGORIES_REQUEST = "HOME_CATEGORIES_REQUEST";

export const VIDEO_PLAYLISTITEMS_SUCCESS = "VIDEO_PLAYLISTITEMS_SUCCESS";
export const VIDEO_PLAYLISTITEMS_FAIL = "VIDEO_PLAYLISTITEMS_FAIL";
export const VIDEO_PLAYLISTITEMS_REQUEST = "VIDEO_PLAYLISTITEMS_REQUEST";
