export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";

export const HOME_PLAYLISTS_SUCCESS = "HOME_PLAYLISTS_SUCCESS";
export const HOME_PLAYLISTS_FAIL = "HOME_PLAYLISTS_FAIL";
export const HOME_PLAYLISTS_REQUEST = "HOME_PLAYLISTS_REQUEST";

export const HOME_CATEGORIES_SUCCESS = "HOME_CATEGORIES_SUCCESS";
export const HOME_CATEGORIES_FAIL = "HOME_CATEGORIES_FAIL";
export const HOME_CATEGORIES_REQUEST = "HOME_CATEGORIES_REQUEST";

export const VIDEO_PLAYLISTITEMS_SUCCESS = "VIDEO_PLAYLISTITEMS_SUCCESS";
export const VIDEO_PLAYLISTITEMS_FAIL = "VIDEO_PLAYLISTITEMS_FAIL";
export const VIDEO_PLAYLISTITEMS_REQUEST = "VIDEO_PLAYLISTITEMS_REQUEST";

export const SELECTED_VIDEO_SUCCESS = "SELECTED_VIDEO_SUCCESS";
export const SELECTED_VIDEO_FAIL = "SELECTED_VIDEO_FAIL";
export const SELECTED_VIDEO_REQUEST = "SELECTED_VIDEO_REQUEST";

export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";
export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";

export const COMMENT_LIST_RELEVANCE_SUCCESS = "COMMENT_LIST_RELEVANCE_SUCCESS";
export const COMMENT_LIST_RELEVANCE_FAIL = "COMMENT_LIST_RELEVANCE_FAIL";
export const COMMENT_LIST_RELEVANCE_REQUEST = "COMMENT_LIST_RELEVANCE_REQUEST";

export const COMMENT_LIST_TIME_SUCCESS = "COMMENT_LIST_TIME_SUCCESS";
export const COMMENT_LIST_TIME_FAIL = "COMMENT_LIST_TIME_FAIL";
export const COMMENT_LIST_TIME_REQUEST = "COMMENT_LIST_TIME_REQUEST";

export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";

export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

export const SET_RATING_STATUS = "SET_RATING_STATUS";
